{"level":"info","message":"Listening on port 3000...","timestamp":"2023-01-03T20:43:57.373Z"}
{"level":"info","message":"Listening on port 3000...","timestamp":"2023-01-03T20:44:12.077Z"}
{"level":"info","message":"Listening on port 3000...","timestamp":"2023-01-03T20:44:28.758Z"}
{"level":"info","message":"Listening on port 3000...","timestamp":"2023-01-03T20:44:37.434Z"}
{"message":"failed to reconnect after 30 attempts with interval 1000 ms","name":"MongoNetworkError","stack":"MongoNetworkError: failed to reconnect after 30 attempts with interval 1000 ms\n    at Connection.<anonymous> (C:\\Users\\10User\\Documents\\Authentication-and-Authorization\\node_modules\\mongodb-core\\lib\\connection\\pool.js:373:13)\n    at Connection.emit (node:events:513:28)\n    at Socket.<anonymous> (C:\\Users\\10User\\Documents\\Authentication-and-Authorization\\node_modules\\mongodb-core\\lib\\connection\\connection.js:245:50)\n    at Object.onceWrapper (node:events:628:26)\n    at Socket.emit (node:events:513:28)\n    at emitErrorNT (node:internal/streams/destroy:157:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:122:3)\n    at processTicksAndRejections (node:internal/process/task_queues:83:21)","level":"error","timestamp":"2023-01-04T17:05:04.511Z"}
{"message":"Topology was destroyed","name":"MongoError","stack":"MongoError: Topology was destroyed\n    at nextFunction (C:\\Users\\10User\\Documents\\Authentication-and-Authorization\\node_modules\\mongodb-core\\lib\\cursor.js:586:27)\n    at Cursor.next [as _next] (C:\\Users\\10User\\Documents\\Authentication-and-Authorization\\node_modules\\mongodb-core\\lib\\cursor.js:789:3)\n    at fetchDocs (C:\\Users\\10User\\Documents\\Authentication-and-Authorization\\node_modules\\mongodb\\lib\\cursor.js:931:10)\n    at toArray (C:\\Users\\10User\\Documents\\Authentication-and-Authorization\\node_modules\\mongodb\\lib\\cursor.js:957:3)\n    at executeOperation (C:\\Users\\10User\\Documents\\Authentication-and-Authorization\\node_modules\\mongodb\\lib\\utils.js:408:22)\n    at Cursor.toArray (C:\\Users\\10User\\Documents\\Authentication-and-Authorization\\node_modules\\mongodb\\lib\\cursor.js:917:10)\n    at C:\\Users\\10User\\Documents\\Authentication-and-Authorization\\node_modules\\mquery\\lib\\collection\\node.js:30:14\n    at handleCallback (C:\\Users\\10User\\Documents\\Authentication-and-Authorization\\node_modules\\mongodb\\lib\\utils.js:128:55)\n    at Collection.find (C:\\Users\\10User\\Documents\\Authentication-and-Authorization\\node_modules\\mongodb\\lib\\collection.js:369:12)\n    at NativeCollection.<computed> [as find] (C:\\Users\\10User\\Documents\\Authentication-and-Authorization\\node_modules\\mongoose\\lib\\drivers\\node-mongodb-native\\collection.js:139:28)\n    at NodeCollection.find (C:\\Users\\10User\\Documents\\Authentication-and-Authorization\\node_modules\\mquery\\lib\\collection\\node.js:26:19)\n    at model.Query.Query._find (C:\\Users\\10User\\Documents\\Authentication-and-Authorization\\node_modules\\mongoose\\lib\\query.js:1327:27)\n    at C:\\Users\\10User\\Documents\\Authentication-and-Authorization\\node_modules\\kareem\\index.js:276:8\n    at C:\\Users\\10User\\Documents\\Authentication-and-Authorization\\node_modules\\kareem\\index.js:23:7\n    at processTicksAndRejections (node:internal/process/task_queues:78:11)","level":"error","timestamp":"2023-01-04T17:06:14.918Z"}
{"message":"failed to reconnect after 30 attempts with interval 1000 ms","name":"MongoNetworkError","stack":"MongoNetworkError: failed to reconnect after 30 attempts with interval 1000 ms\n    at Connection.<anonymous> (C:\\Users\\10User\\Documents\\Authentication-and-Authorization\\node_modules\\mongodb-core\\lib\\connection\\pool.js:373:13)\n    at Connection.emit (node:events:513:28)\n    at Socket.<anonymous> (C:\\Users\\10User\\Documents\\Authentication-and-Authorization\\node_modules\\mongodb-core\\lib\\connection\\connection.js:245:50)\n    at Object.onceWrapper (node:events:628:26)\n    at Socket.emit (node:events:513:28)\n    at emitErrorNT (node:internal/streams/destroy:157:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:122:3)\n    at processTicksAndRejections (node:internal/process/task_queues:83:21)","level":"error","timestamp":"2023-01-04T17:19:55.356Z"}
